name: 'Publish Docker images'
description: 'Publish Docker images; PyPI packages must already be published'
inputs:
  version:
    description: 'Version number (e.g. 0.1.1rc2, 0.1.1.dev20250201)'
    required: true
    type: string
  templates:
    description: 'Optional comma-separated templates to publish'
    required: false
    type: string
  dockerhub_username:
    description: 'DockerHub username'
    required: true
    type: string
  dockerhub_token:
    description: 'DockerHub token'
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        enable-cache: false

    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Build and publish
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        TEMPLATES: ${{ inputs.templates }}
      run: |
        chmod +x ${{ github.action_path }}/main.sh
        ${{ github.action_path }}/main.sh

# Example usage in workflow:
# - uses: meta-llama/llama-stack-ops/actions/commit-final-packages@main
#   with:
#     version: '1.0.0'
#     pypi_token: ${{ secrets.PYPI_TOKEN }}
