name: Publish Package to NPM

on:
  workflow_dispatch:  # Keep manual trigger
    inputs:
      version:
        description: 'Version number (e.g. 0.1.1rc2, 0.1.1.dev20250201)'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: meta-llama/llama-stack-client-typescript  # Replace with the actual owner/repo-name
          path: ./llama-stack-client-typescript
          token: ${{ secrets.LLAMA_REPOS_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
          cache-dependency-path: './llama-stack-client-typescript/yarn.lock'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd llama-stack-client-typescript
          yarn version --new-version ${{ inputs.version }} -m "Bump version to ${{ inputs.version }}" --no-git-tag-version
          yarn install
          yarn build
          cd dist
          yarn publish --tag rc --non-interactive --access public
          cd ..
