name: Test published package

on:
  workflow_dispatch:  # Keep manual trigger
    inputs:
      version:
        description: 'Version number (e.g. 0.1.1rc2, 0.1.1.dev20250201)'
        required: true
        type: string

jobs:
  test-published-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/test-published-package
      with:
        version: ${{ inputs.version }}
