name: Test and Possibly Cut a Branch

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID'
        required: true
      client_python_commit_id:
        description: 'llama-stack-client-python commit ID'
        required: false
        type: string
        default: 'origin/main'
      version:
        description: 'Version (e.g. 0.1.1rc2); if optional, will not cut a branch'
        required: false
        type: string
      cut_mode:
        description: 'Mode to run the script in (test-and-cut, test-only, cut-only)'
        required: false
        type: string
        default: 'test-and-cut'
      template:
        description: 'Template to use for the release candidate'
        required: false
        type: string
        default: 'fireworks'
  schedule:
    - cron: "0 0 * * *"  # Run every day at midnight

jobs:
  test-and-maybe-cut:
    runs-on: ubuntu-latest
    environment:
      name: testrelease
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set commit ID and version for scheduled runs
      id: inputs
      run: |
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          echo "commit_id=origin/main" >> $GITHUB_OUTPUT
          echo "version=" >> $GITHUB_OUTPUT
          echo "client_python_commit_id=origin/main" >> $GITHUB_OUTPUT
        else
          echo "commit_id=${{ inputs.commit_id }}" >> $GITHUB_OUTPUT
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "client_python_commit_id=${{ inputs.client_python_commit_id }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Set version if not provided
      id: version
      run: |
        if [ -z "${{ steps.inputs.outputs.version }}" ]; then
          echo "value=0.0.0.dev$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "cut_mode=test-and-cut" >> $GITHUB_OUTPUT
        else
          echo "value=${{ steps.inputs.outputs.version }}" >> $GITHUB_OUTPUT
          echo "cut_mode=${{ steps.inputs.outputs.cut_mode }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - uses: ./actions/test-and-cut
      with:
        version: ${{ steps.version.outputs.value }}
        commit_id: ${{ steps.inputs.outputs.commit_id }}
        client_python_commit_id: ${{ steps.inputs.outputs.client_python_commit_id }}
        template: ${{ inputs.template }}
        cut_mode: ${{ steps.version.outputs.cut_mode }}
        fireworks_api_key: ${{ secrets.FIREWORKS_API_KEY }}
        together_api_key: ${{ secrets.TOGETHER_API_KEY }}
        tavily_search_api_key: ${{ secrets.TAVILY_SEARCH_API_KEY }}
        # TODO: this will expire in 90 days; we should figure out a
        # GitHub App setup that can be used instead
        github_token: ${{ secrets.LLAMA_REPOS_PAT }}
