name: Test published package

on:
  workflow_dispatch:  # Keep manual trigger
    inputs:
      version:
        description: 'Version number (e.g. 0.1.1rc2, 0.1.1.dev20250201)'
        required: true
        type: string
      template:
        description: 'Template to use for the release candidate (fireworks, together) (default: fireworks)'
        required: false
        type: string
        default: 'fireworks'

jobs:
  test-published-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./actions/test-published-package
      with:
        version: ${{ inputs.version }}
        together_api_key: ${{ secrets.TOGETHER_API_KEY }}
        tavily_search_api_key: ${{ secrets.TAVILY_SEARCH_API_KEY }}
        fireworks_api_key: ${{ secrets.FIREWORKS_API_KEY }}
        template: ${{ inputs.template }}
